### ISSUE TITLE
EC function from Secp256K1 mixing modules values

### ISSUE THREAD

**Issue by albertobsd** [JeanLucPons/Kangaroo#108]
There are some mixing used different Values from Modulo operation inside the EC function

There are two values _P and _O static in the Int Class

```P = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F```

```O = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141```

the functions `ModSquareK1 `and `ModMulK1 ` use Mod O

but the functions `ModAdd `and `ModSub` use Mod P

AFAIK for this Operation all should be Mod O, 

```
bool Secp256K1::EC(Point &p) {
	Int _s;
	Int _p;
	_s.ModSquareK1(&p.x);
	_p.ModMulK1(&_s,&p.x);
	_p.ModAdd(7);
	_s.ModMulK1(&p.y,&p.y);
	_s.ModSub(&_p);
	return _s.IsZero(); // ( ((pow2(y) - (pow3(x) + 7)) % P) == 0 );
}
```

Since `_s.ModSub(&_p);` is using mod _P i think that this maybe lead in some false Negatives, but it need to be tested and also corrected to avoid ambiguities

**Comment by albertobsd** [comment]
Never mind

**Comment by secp8x32** [comment]
Both `ModSquareK1` and `ModMulK1` are using Mod P, and whenever we need to deal with field elements, we need to use Mod P because that's our prime field.

The functions that are using Mod O are ends with `order` suffix, like `void ModMulK1order(Int *a)`, `void ModAddK1order(Int *a,Int *b)` etc, see `Int.h` and `IntMod.cpp`.

And the function `bool Secp256K1::EC(Point &p)` is directly dealing with field elements so every operation will be Mod P.

**Comment by albertobsd** [comment]
Thank you, yes i agree with you now, i realize of this in the code yesterday that is why i close it.

**Comment by secp8x32** [comment]
Okay, never mind
