### ISSUE TITLE
@jeanLucPons really appreciate. 

### ISSUE THREAD

**Issue by futuremoneybtc** [JeanLucPons/Kangaroo#14]
Will you add this [quarry](https://blockchain.info/q/pubkeyaddr/1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH) where we input multiple used bitcoin addresses and through that quarry kangaroo will convert these addresses to public key and start searching in full range 0 to fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140 and one more thing search will be random if possible.

**Comment by RB61** [comment]
> Will you add this [quarry](https://blockchain.info/q/pubkeyaddr/1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH) where we input multiple used bitcoin addresses and through that quarry kangaroo will convert these addresses to public key and start searching in full range 0 to fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140 and one more thing search will be random if possible.

You may be confusing this program with https://github.com/brichard19/BitCrack

**Comment by djarumlights** [comment]
Right, the kangaroo method is already random by nature. Well, pseudorandom, as the science folks write, at least. Besides, not every address has a pubkey floating around on the chain. You'd end up filtering out a large chunk of your list, most likely. Best to just do the legwork and make your own list of pubkeys.

**Comment by futuremoneybtc** [comment]
> Right, the kangaroo method is already random by nature. Well, pseudorandom, as the science folks write, at least. Besides, not every address has a pubkey floating around on the chain. You'd end up filtering out a large chunk of your list, most likely. Best to just do the legwork and make your own list of pubkeys.

**Comment by futuremoneybtc** [comment]
Nice to hear that kangaroo method is already random you mean to say when i start the search from 0 to fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140 every time it will start random counting with different numbers not sequential am I right ??.. and i am talking about both randomness in the numbers and the range too.

**Comment by djarumlights** [comment]
I'm not a high math aficionado by any means and don't understand exactly how to explain it, but yes. 

To get an idea of what exactly is going on, glance at this: https://web.northeastern.edu/seigen/11Magic/KruskalsCount/PollardKangarooMonopoly.pdf
You can find more if you look for Telariust's github. He linked to a couple more papers about it. 

I can't even begin to explain to you what any of that means, but logic tells me it's a substantial amount of effort that I visualize being akin to the cards bouncing around when you win at Solitaire on an old windows PC. Bear in mind that fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140 is a HUGE number. Even the range from 1F000000000000000000000000000000000000000000000000 to 2F000000000000000000000000000000000000000000000000 is gigantic when converted to decimal (regular ol' numbers). Counting between these two numbers whether sequentially or randomly will take a LONG time unless by freak chance one of the random jumps between tame/wild HAPPENS to cross the correct path. That's the main benefit of kangaroo: it introduces the freak chance as being possible by looking for an intersecting point on a graph instead (JLP, if I'm an idiot and completely wrong about this, PLEASE correct me!)

So this is all still a game of chance with the odds stacked very much against we who are questing for whatever we're questing for. Except with this, we're waiting for a couple of animals to fight each other instead of just going "uhh, one, uhhhh two, uhhhh threeee. . . . what come after three in countin', pappy?"

**Comment by djarumlights** [comment]
Actually, I just saw the link JLP put into the readme. It has a very good summary towards the end:

> As with the rho method, the kangaroo method relies on a pseudorandom
walk, however steps in the kangaroo walk correspond to known small increments
in the exponent (in other words, kangaroos make small jumps). The tame kangaroo starts in the middle of the interval (i.e., at g
N/2
) and jumps towards the
right. The wild kangaroo starts at the group element h and jumps to the right
using the same pseudorandom walk. On a serial computer one alternately jumps
the tame and wild kangaroos. Every now and then a tame or wild kangaroo
lands on a distinguished group element u and stores it in a sorted list, binary
tree or hash table together with its discrete logarithm (if the kangaroo is tame)
or the discrete logarithm of uh−1
(if the kangaroo is wild). Once the same group
element is visited twice by different kangaroos the DLP is solved.

**Comment by futuremoneybtc** [comment]
Very informative answers thanks.. hope these two kangaroos help me to solve atleast puzzle no. 110... 20 hours is almost done better if we have checkpoints here as jeanLucPons says hope soon these requirements are also available here.

**Comment by RB61** [comment]
> Very informative answers thanks.. hope these two kangaroos help me to solve atleast puzzle no. 110... 20 hours is almost done better if we have checkpoints here as jeanLucPons says hope soon these requirements are also available here.

20 hours ???    20MKeys/s  requires 100 Years
if you can do it in 20 hours it means you can do 855 GKeys/s

**Comment by kpot87** [comment]
> > Very informative answers thanks.. hope these two kangaroos help me to solve atleast puzzle no. 110... 20 hours is almost done better if we have checkpoints here as jeanLucPons says hope soon these requirements are also available here.
> 
> 20 hours ??? 20MKeys/s requires 100 Years
> if you can do it in 20 hours it means you can do 855 GKeys/s

Why not 850 RTX2080ti :)

**Comment by futuremoneybtc** [comment]
I notice one more thing 4 keys of 64 bits range in 5 minutes but every time they start counting from the beginning if they count continues instead of beginning it will be more efficient for us. i think they count particular pubkey not bunch of pubkey at a time.

Kangaroo v1.3
Start:0
Stop :FFFFFFFFFFFFFFFF
Keys :4
Number of CPU thread: 6
Range width: 2^64
Number of random walk: 2^18.61 (Max DP=11)
DP size: 11 [0xFFE0000000000000]
SolveKeyCPU Thread 0: 1024 kangaroos
SolveKeyCPU Thread 2: 1024 kangaroos
SolveKeyCPU Thread 3: 1024 kangaroos
SolveKeyCPU Thread 4: 1024 kangaroos
SolveKeyCPU Thread 5: 1024 kangaroos
SolveKeyCPU Thread 1: 1024 kangaroos
GPU: GPU #0 GeForce GTX 1050 Ti (6x128 cores) Grid(12x256) (45.0 MB used)
SolveKeyGPU Thread GPU#0: creating kangaroos...
SolveKeyGPU Thread GPU#0: 2^18.58 kangaroos in 1769.3ms
[155.99 MKey/s][GPU 116.95 MKey/s][Count 2^33.84][Dead 0][01:49][576.3MB]
Key# 0 Pub:  0x035CDFF6F0F199C79C9AC48844DC1B596947D93C1D2312C8BD9D4D1BB38B4AD8CD
       Priv: 0xB0F0222680C5916E
[157.43 MKey/s][GPU 117.80 MKey/s][Count 2^33.71][Dead 0][01:40][529.0MB]
Key# 1 Pub:  0x030F37D887640448C993CD8F84DC9B41E1BE6655DCCE5499A6F430BD617BFADE08
       Priv: 0xB0F0222BE723D382
[158.67 MKey/s][GPU 119.18 MKey/s][Count 2^33.87][Dead 2][01:52][588.2MB]
Key# 2 Pub:  0x024B7E0ABCE535415043AA8D750D290A9904AA9E397B072DD214786BD1DD615FD1
       Priv: 0xB0F0223074A94229
[162.83 MKey/s][GPU 122.54 MKey/s][Count 2^31.49][Dead 0][22s][117.6MB]
Key# 3 Pub:  0x02E37CA3939BD44A271AFD058C2C3A0F7B4F28093205A42CCE46BB8FA77D9C88E0
       Priv: 0xB0F0223253B462C1

Done: Total time 05:53

**Comment by djarumlights** [comment]
Right now it does count one by one. Concurrent ops and checkpoints are forthcoming I think maybe (and that will be wicked cool). 

And yeah, 110 bit puzzle. . . . I'm looking at 11 more years right now after 2 days (and that's only because I've stopped several times whether to update version or had to shut down due to bad weather), so . . . . sit back, relax, have yourself a cup of preferred beverage. . . ^_^ The race is on!

**Comment by RB61** [comment]
> > > Very informative answers thanks.. hope these two kangaroos help me to solve atleast puzzle no. 110... 20 hours is almost done better if we have checkpoints here as jeanLucPons says hope soon these requirements are also available here.
> > 
> > 
> > 20 hours ??? 20MKeys/s requires 100 Years
> > if you can do it in 20 hours it means you can do 855 GKeys/s
> 
> Why not 850 RTX2080ti :)

RTX2080TI gives 850MKeys/s not 850GKeys  :)

**Comment by RB61** [comment]
> > > Very informative answers thanks.. hope these two kangaroos help me to solve atleast puzzle no. 110... 20 hours is almost done better if we have checkpoints here as jeanLucPons says hope soon these requirements are also available here.
> > 
> > 
> > 20 hours ??? 20MKeys/s requires 100 Years
> > if you can do it in 20 hours it means you can do 855 GKeys/s
> 
> Why not 850 RTX2080ti :)

True :)  but 850 x RTX2080TI cost more that's  850 000  dollars ! lol

**Comment by MrFreeDragon** [comment]
> > Why not 850 RTX2080ti :)
> 
> True :) but 850 x RTX2080TI cost around 850 000 dollars ! lol

There is no need to buy 850 cards. You can just rent them for 20-24 hours. If you can rent 4xRTX2080ti for 25-30usd/day, so you have to pay 5-6.5 kUSD, and with 50% probability you will find the key to 110bit puzzle address worth prize 9.9k

Looks like a game with zero-expectation :) 5k usd investment, and the profit 50% * 9.9k = ~5k --> 0k expected profit )
