### ISSUE TITLE
Ram

### ISSUE THREAD

**Issue by kpot87** [JeanLucPons/Kangaroo#9]
Hi  JLP! What will be if all RAM memory of PC will be full? And when it’s possible to restart script if speed is decreased? I mean for rxample if my normal speed is 830m when it’s going down to 100 or 30 it’s ty to no waist a time and change bit to higher. Or when all rang will scan and nothing found it’s show the info like “nothing found”? Thanks

**Comment by JeanLucPons** [comment]
Hi,
You have to adjust your setting in order to minimize RAM usage and try to get the best performances. Too large grid(s) for too small range generate a large memory usage with the default dp calculation.
You can also increase the DP size using the -d option but take in consideration that the overhead is about nbKangoroo * 2^dp supplementary operations.

**Comment by djarumlights** [comment]
@kpot87 I ran into the same thing. It takes some try/fail to find what works for smaller ranges (or just sticking to CPU for those).

On a semi-related note, would one want to use a larger grid for a larger range or am I visualizing the process incorrectly? As a person grossly unfamiliar with higher math, I am trying to apply logic to how the process works by picturing a grid, an elliptic curve, and the hypothetical kangaroos going in various fixed or random patterns across it.

**Comment by djarumlights** [comment]
I just compiled the most recent changes that have the expected # of operations, etc. This helps paint a better picture of potential RAM usage and such. Good good!

**Comment by JeanLucPons** [comment]
Ok
These values (expected operation and RAM) are still under development. Need more math to give good approximations.

**Comment by djarumlights** [comment]
For FYI

![image](https://user-images.githubusercontent.com/57685542/80321908-b8bf6400-87e6-11ea-9774-be0a7ded37e4.png)

**Comment by CatfishCrypt** [comment]
@djarumlights how are you computing your new additions? Expected operations and expected RAM?

**Comment by JeanLucPons** [comment]
I'm working on it, it is a tricky and difficult problem:

N = range
dp = distinguished bit number

Expected operations: 2.sqrt(N) + nbKangaroo.2^dp (but this an asymptote for small nbKangaroo compare to 2^dp, in fact it is less, in the order of cubicRoot(nbKangaroo.N.2^dp) when nbKangaroo >> sqrt(N) - 2^dp )

Expected memory: sizeof(point) * expectedOperation/2^dp

**Comment by CatfishCrypt** [comment]
Seems very tricky.  It's just a guesstimate, right? Maybe add the "mamma mia" line if it's over a certain number? :)

**Comment by djarumlights** [comment]
@CatfishCrypt Oh, I can't code my way out of a wet paper bag that's already been torn partially! I just compiled the changes JLP made since the last release to test them (now that I've halfway figured out how to stumble around that process).

For some add'l insight on RAM usage being shown vs actual, please see the attached screenshots.
![image](https://user-images.githubusercontent.com/57685542/80400103-f3290f80-887f-11ea-84f6-812cf215ec25.png)

![image](https://user-images.githubusercontent.com/57685542/80400156-03d98580-8880-11ea-99a7-5b2086ba1b31.png)
I do have other things open like Chrome, an email client, and Discord, so that's affecting actual VRAM.

![image](https://user-images.githubusercontent.com/57685542/80400245-24094480-8880-11ea-8738-b5cd58fa9deb.png)

Hope this is useful data!

**Comment by kozsv** [comment]
tell me how to register a grid for two cards?
